[package]
name = "risingwave_connector"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
apache-avro = { git = "https://github.com/risingwavelabs/avro", rev = "d0846a16ce813a225af04ade35b3b8117b137a29", features = [
    "snappy",
    "zstandard",
    "bzip",
    "xz",
] }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
async-nats = "0.33"
async-trait = "0.1"
auto_enums = { version = "0.8", features = ["futures03"] }
auto_impl = "1"
aws-config = { workspace = true }
aws-credential-types = { workspace = true }
aws-sdk-kinesis = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-smithy-http = { workspace = true }
aws-smithy-runtime-api = { workspace = true }
aws-smithy-types = { workspace = true }
aws-types = { workspace = true }
base64 = "0.21"
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
clickhouse = { git = "https://github.com/risingwavelabs/clickhouse.rs", rev = "622501c1c98c80baaf578c716d6903dde947804e", features = [
    "time",
] }
csv = "1.3"
deltalake = { workspace = true }
duration-str = "0.7.0"
easy-ext = "1"
enum-as-inner = "0.6"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
gcp-bigquery-client = "0.18.0"
glob = "0.3"
google-cloud-pubsub = "0.22"
http = "0.2"
hyper = { version = "0.14", features = [
    "client",
    "tcp",
    "http1",
    "http2",
    "stream",
] }
hyper-tls = "0.5"
icelake = { workspace = true }
indexmap = { version = "1.9.3", features = ["serde"] }
itertools = "0.12"
jni = { version = "0.21.1", features = ["invocation"] }
jst = { package = 'jsonschema-transpiler', git = "https://github.com/mozilla/jsonschema-transpiler", rev = "c1a89d720d118843d8bcca51084deb0ed223e4b4" }
maplit = "1.0.2"
moka = { version = "0.12", features = ["future"] }
mysql_async = { version = "0.33", default-features = false, features = [
    "default",
] }
mysql_common = { version = "0.31", default-features = false, features = [
    "chrono",
] }
nexmark = { version = "0.2", features = ["serde"] }
num-bigint = "0.4"
opendal = "0.44"
parking_lot = "0.12"
paste = "1"
prometheus = { version = "0.13", features = ["process"] }
prost = { version = "0.12", features = ["no-recursion-limit"] }
prost-reflect = "0.12"
prost-types = "0.12"
protobuf-native = "0.2.1"
pulsar = { version = "6.1", default-features = false, features = [
    "tokio-runtime",
    "telemetry",
    "auth-oauth2",
] }
rdkafka = { workspace = true, features = [
    "cmake-build",
    # "ssl",
    # FIXME: temporary workaround before we find an ideal solution.
    # See why it's needed and why it's not ideal in https://github.com/risingwavelabs/risingwave/issues/9852
    "ssl-vendored",
    "gssapi",
    "zstd",
] }
redis = { version = "0.24.0", features = ["aio","tokio-comp","async-std-comp"] }
regex = "1.4"
reqwest = { version = "0.11", features = ["json"] }
risingwave_common = { workspace = true }
risingwave_jni_core = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
rust_decimal = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_derive = "1"
serde_json = "1"
serde_with = { version = "3", features = ["json"] }
simd-json = "0.13.3"
strum = "0.25"
strum_macros = "0.25"
tempfile = "3"
thiserror = "1"
time = "0.3.30"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-postgres = "0.7"
tokio-retry = "0.3"
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec", "io"] }
tonic = "0.10.2"
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["futures-03"] }
url = "2"
urlencoding = "2"
with_options = { path = "./with_options" }
yup-oauth2 = "8.3"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio", "async"] }
deltalake = { workspace = true, features = ["datafusion"] }
expect-test = "1"
pretty_assertions = "1"
quote = "1"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
syn = { version = "1", features = ["full"] }
tempfile = "3"
tracing-subscriber = "0.3"
tracing-test = "0.2"
walkdir = "2"

[build-dependencies]
prost-build = "0.12"
protobuf-src = "1"

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "nexmark_integration"
harness = false

[lints]
workspace = true
