[package]
name = "risingwave_frontend"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
arc-swap = "1"
arrow-schema = { workspace = true }
async-recursion = "1.0.5"
async-trait = "0.1"
auto_enums = { version = "0.8", features = ["futures03"] }
auto_impl = "1"
bk-tree = "0.5.0"
bytes = "1"
clap = { version = "4", features = ["derive"] }
ctor = "0.2"
downcast-rs = "1.2"
dyn-clone = "1.0.14"
easy-ext = "1"
educe = "0.5"
either = "1"
enum-as-inner = "0.6"
fixedbitset = "0.4.2"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
iana-time-zone = "0.1"
icelake = { workspace = true }
itertools = "0.12"
maplit = "1"
md5 = "0.7.0"
num-integer = "0.1"
parking_lot = "0.12"
parse-display = "0.8"
paste = "1"
petgraph = "0.6"
pgwire = { path = "../utils/pgwire" }
pin-project-lite = "0.2"
postgres-types = { version = "0.2.6" }
pretty-xmlish = "0.1.13"
pretty_assertions = "1"
prometheus = { version = "0.13", features = ["process"] }
rand = "0.8"
risingwave_batch = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_service = { workspace = true }
risingwave_connector = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
risingwave_source = { workspace = true }
risingwave_sqlparser = { workspace = true }
risingwave_storage = { workspace = true }
risingwave_udf = { workspace = true }
risingwave_variables = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.7"
smallvec = { version = "1.11.1", features = ["serde"] }
tempfile = "3"
thiserror = "1"
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-stream = "0.1"
tonic = { workspace = true }
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["futures-03"] }
uuid = "1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
risingwave_expr_impl = { workspace = true }
tempfile = "3"

[lints]
workspace = true
